alias dir="dir --color=auto"
alias vdir="vdir --color=auto"

alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

alias l="ls -CF"
alias ll="ls -l"
alias la="ls -A"
alias lal="ls -Alh"
